export default [
  {
    title: "CBA",
    publishDateTime: "2022-11-07T21:10:00Z",
    image: {
      src: "/images/paintings/cba.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Paint Ting and Tingker Bell are standing.",
        "Paint Ting asks, 'Why are we going to do?'.",
        "Tingker Bell replies, 'About what?'.",
        "In the top right panel, Tingker Bell thinks and Paint Ting informs, 'You know, about the fact that we don't have a side fringe anymore...'.",
        "In the bottom left panel, Tingker Bell smiles and says 'Oh... Well, can you be bothered to redesign me and all the other Tings.'.",
        "Paint Ting bluntly replies, 'No.'.",
        "In the bottom right panel, Tingker Bell laughs and says, 'Nothing it is then!'.",
        "Paint Ting celebrates with their arms up and their paint brush in the air.",
      ].join(" "),
    },
    tags: ["Paint Ting", "Tingker Bell"],
  },
  {
    title: "Pain",
    publishDateTime: "2022-11-05T22:00:00Z",
    image: {
      src: "/images/paintings/pain.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Paint Ting and Tingker Bell are standing.",
        "Paint Ting asks, 'Why haven't you asked me to create any paintings?'.",
        "In the top right panel, Tingker Bell thinks and replies, 'Well...'.",
        "In the bottom left panel, a car drifting right with a sign above.",
        "The direction ahead says 'Making paints' and the direction right says 'Only seeing the pain in paintings'.",
        "In the bottom right panel, Paint Ting stands with a neutral expression and says 'This didn't last long...'.",
      ].join(" "),
    },
    tags: ["Paint Ting", "Tingker Bell"],
  },
  {
    title: "Emperor King Yusuf",
    publishDateTime: "2021-01-21T17:43:00Z",
    image: {
      src: "/images/paintings/emperor-king-yusuf-character-bio.png",
      alt: [
        "A character biography of Emperor King Yusuf.",
        "Age is 786.",
        "Height is 7.3 bananas.",
        "Random facts include: they own the world;",
        "they love sleeping;",
        "they wear a cape in the hopes of being able to fly;",
        "they get bullied by Tingker Bell.",
      ].join(" "),
    },
    tags: ["Emperor King Yusuf"],
  },
  {
    title: "Quoting Emperor King Yusuf",
    publishDateTime: "2021-01-19T18:55:00Z",
    image: {
      src: "/images/paintings/quoting-emperor-king-yusuf.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, it's dated 8th July 2021 at 14:02 and Emperor King Yusuf is pondering and Tingker Bell has a straight face.",
        "Emperor King Yusuf asks 'I was thinking about this in the morning, but are you low key emo?'.",
        "In the top right panel, it's dated 4th August 2020 at 12:47 and Emperor King Yusuf with a small smile is thinking.",
        "Emperor King Yusuf asks 'If I call you fattie, will you be offended?' and Tingker Bell replies with a big smile.",
        "In the bottom left panel, it's dated 19th August 2020 at 13:55 and Emperor King Yusuf has their arms up in shock saying 'You have friends? Awww.'",
        "Tingker Bell shrugs back with a smile.",
        "In the bottom right panel, it's dated 9th October 2020 at 08:57 and Emperor King Yusuf has their famous smirk on and says 'Physically 12, mentally 12 but actually 23.'.",
        "Tingker Bell smiles whilst reaching out to Emperor King Yusuf like a child.",
      ].join(" "),
    },
    tags: ["Emperor King Yusuf", "Tingker Bell"],
  },
  {
    title: "Repeat Ting",
    publishDateTime: "2021-01-17T20:53:00Z",
    image: {
      src: "/images/paintings/repeat-ting-character-bio.png",
      alt: [
        "A character biography of Repeat Ting.",
        "Age is 555.",
        "Height is 3.69 bananas.",
        "Random facts include: they're Interrogate Ting's arch-enemy;",
        "their favourite song is Repeat Until Death by Novo Amor;",
        "in secondary school, they won a dance competition which earned them a £30 gift voucher for the cinema;",
        "their favourite song is Repeat Until Death by Novo Amor.",
      ].join(" "),
    },
    tags: ["Repeat Ting"],
  },
  {
    title: "Stop it",
    publishDateTime: "2021-01-16T17:32:00Z",
    image: {
      src: "/images/paintings/stop-it.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Repeat Ting and Tingker Bell are standing.",
        "Tingker Bell greets Repeat Ting with a wave, saying 'Hey Repeat Ting!' and Repeat Ting replies with 'Hey Repeat Ting'.",
        "In the top right panel, Tingker Bell angrily tells Repeat Ting to stop it but Repeat Ting replies with 'Stop it!'.",
        "In the bottom left panel, Tingker Bell smiles and says 'I'm going to get Assassinate Ting'.",
        "In the bottom right panel, Repeat Ting at the forefront with cat ears and whiskers is scared whilst Tingker Bell smiles in the background.",
      ].join(" "),
    },
    tags: ["Repeat Ting", "Tingker Bell"],
  },
  {
    title: "Finding puns",
    publishDateTime: "2021-01-13T21:21:00Z",
    image: {
      src: "/images/paintings/finding-puns.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Detect Ting is on a beach with a pun detector.",
        "Behind them are holes in the sand with words such as farting, miscalculating, splitting and skywriting.",
        "In the top right panel, Detect Ting shouts 'Hey, I found a word!' and Tingker Bell appears waving.",
        "In the bottom left panel, Detect Ting is digging up a hole with a shovel whilst Tingker Bell asks 'What word is it?'.",
        "In the bottom right panel, Detect Ting holds up the word 'detecting' with a massive smile.",
        "Tingker Bell facepalms and says 'For f**k's sake.'.",
      ].join(" "),
    },
    tags: ["Detect Ting", "Tingker Bell"],
  },
  {
    title: "Detect Ting",
    publishDateTime: "2021-01-13T21:20:00Z",
    image: {
      src: "/images/paintings/detect-ting-character-bio.png",
      alt: [
        "A character biography of Detect Ting.",
        "Age is 46.",
        "Height is 3.69 bananas.",
        "Random facts include: bullshit, not puns, is their favourite thing to detect;",
        "they caused Tingker Bell to facepalm 1,997 times and counting;",
        "they have a goldfish named Decker;",
        "they solved the murder committed by Sharpshoot Ting.",
      ].join(" "),
    },
    tags: ["Detect Ting"],
  },
  {
    title: "Hate Ting",
    publishDateTime: "2021-01-13T21:19:00Z",
    image: {
      src: "/images/paintings/hate-ting-character-bio.png",
      alt: [
        "A character biography of Hate Ting.",
        "Age is 666.",
        "Height is 3.69 bananas.",
        "Random facts include: they had a starring role in Direct Ting's musical rendition of She-Ra and the Princesses of Power;",
        "they loved something once but decided never again;",
        "a month ago ordered a life-sized cardboard figure of Taylor Swift but it turned out to only be the height of half a banana;",
        "they once danced the night away.",
      ].join(" "),
    },
    tags: ["Hate Ting"],
  },
  {
    title: "Meta Ting",
    publishDateTime: "2021-01-13T21:18:00Z",
    image: {
      src: "/images/paintings/meta-ting-character-bio.png",
      alt: [
        "A character biography of Meta Ting.",
        "Age is 41.",
        "Height is 3.69 bananas.",
        "Random facts include: the first time they broke the fourth wall, they broke their hand;",
        "they once went backpacking across western Europe;",
        "they don't understand how Paint Ting didn't notice they made one side of their hair longer than the other;",
        "the last random fact for them was changed 4 times before settling on this crap.",
      ].join(" "),
    },
    tags: ["Meta Ting"],
  },
  {
    title: "Paint Ting",
    publishDateTime: "2021-01-13T21:17:00Z",
    image: {
      src: "/images/paintings/paint-ting-character-bio.png",
      alt: [
        "A character biography of Paint Ting.",
        "Age is 1.",
        "Height is 3.69 bananas.",
        "Random facts include: they once applied for teacher training;",
        "they hold a paint brush even though they use the pencil tool in Microsoft Paint;",
        "their first painting was a boat, created in December 2019;",
        "they didn't realise they drew Tingker Bell without glasses until 6 months later.",
      ].join(" "),
    },
    tags: ["Paint Ting"],
  },
  {
    title: "You f**k up",
    publishDateTime: "2021-01-10T14:33:00Z",
    image: {
      src: "/images/paintings/you-f__k-up.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, is a flashback to first comic - I am Tingker Bell.",
        "In the top right panel, Hate Ting is on the left and says 'You f**k up. The colour order doesn't match Blur's album cover'.",
        "Paint Ting shrugs and replies 'I tried'.",
        "In the bottom left panel, is a flashback to the bottom left panel of the previous comic - It actually doesn't make sense comic.",
        "In the bottom right panel, Hate Ting says 'You f**k up. Meta Ting is supposed to be smoller because they're further away.'",
        "Paint Ting replied 'Yeah, I don't care.'.",
      ].join(" "),
    },
    tags: ["Hate Ting", "Paint Ting", "Tingker Bell", "Meta Ting"],
  },
  {
    title: "It actually doesn't make sense",
    publishDateTime: "2021-01-09T23:02:00Z",
    image: {
      src: "/images/paintings/it-actually-doesnt-make-sense.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Paint Ting and Tingker Bell are standing next to each other.",
        "Paint Ting has a paint brush against Tingker Bell's face.",
        "In the top right panel, Paint Ting has small ducks around over their head and scratching their head in confusion.",
        "Paint Ting says 'Y'know, it actually doesn't make sense for you to have both wings on one side when you're not flying...'.",
        "In the bottom left panel, Paint Ting has a raised eyebrow and Tingker Bell is shrugging with a smile.",
        "Tingker Bell says 'Yeah, but it makes it easier for you to draw me.'.",
        "In the bottom right panel, Meta Ting appears and says 'Ah, meta shit.'",
      ].join(" "),
    },
    tags: ["Tingker Bell", "Paint Ting", "Meta Ting"],
  },
  {
    title: "Nope",
    publishDateTime: "2021-01-09T22:56:00Z",
    image: {
      src: "/images/paintings/nope.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Tingker Bell is standing outside a hedge.",
        "In the top right panel, Tingker Bell is slighting into the hedge.",
        "In the bottom left panel, Tingker Bell is inside the hedge with only their face and belly visible.",
        "In the bottom right panel, Tingker Bell is completely immersed in the hedge.",
      ].join(" "),
    },
    tags: ["Tingker Bell"],
  },
  {
    title: "Some Tings",
    publishDateTime: "2021-01-09T22:51:00Z",
    image: {
      src: "/images/paintings/some-tings.png",
      alt: [
        "4 panel comic.",
        "In the top left panel with a title 'Miscalculate Ting', Tingker Bell is calculating that 1 + 1 = a window.",
        "In the top right panel with a title 'Split Ting', Tingker Bell is split into half with a gap in-between each.",
        "In the bottom left panel with a title 'Fart Ting', Tingker Bell is cheerful and off the ground like a rocket with dark green 'smoke'.",
        "In the bottom right panel with a title 'Skywrite Ting', Tingker Bell flying with clouds that spell out 'Skywrite Ting'.",
      ].join(" "),
    },
    tags: ["Miscalculate Ting", "Split Ting", "Fart Ting", "Skywrite Ting"],
  },
  {
    title: "I am Tingker Bell",
    publishDateTime: "2021-01-09T22:50:00Z",
    image: {
      src: "/images/paintings/i-am-tingker-bell.png",
      alt: [
        "4 panel comic.",
        "In the top left panel, Tingker Bell's face is at the forefront with a cute smile on a yellow background.",
        "In the top right panel, Tingker Bell's face is at the forefront with a straight mouth on a blue background.",
        "In the bottom left panel, Tingker Bell's face is at the forefront with a big smile on a pink background.",
        "In the bottom right panel, Tingker Bell's face is at the forefront with a shocked expression on a green background.",
      ].join(" "),
    },
    tags: ["Tingker Bell"],
  },
];
