#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn format
yarn lint

stagedJavaScriptFiles=$(git diff --cached --name-only -- "*.js" "*.jsx")

if [ ${#stagedJavaScriptFiles} -gt 0 ]; then
  yarn test:unit
fi
