name: CD

on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      vercel-org-id:
        required: true
      vercel-project-id:
        required: true

jobs:
  deploy:
    name: 🚀 Deploy to production
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    concurrency: deployment
    environment:
      name: Production
      url: https://wentingwang.co.uk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Download built project
        uses: actions/download-artifact@v3
        with:
          name: project
          path: .next

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: .vercel/output

      - name: Deploy built project to production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.vercel-token }}
