name: CD

on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      vercel-org-id:
        required: true
      vercel-project-id:
        required: true

jobs:
  deploy-to-preview:
    name: 👀 Deploy to preview
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    environment:
      name: Preview
      url: ${{ steps.preview-deployment-url.outputs.url }}
    outputs:
      preview-deployment-url: ${{ steps.preview-deployment-url.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull preview environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.vercel-token }}

      - name: Build project
        run: vercel build --token=${{ secrets.vercel-token }}

      - name: Deploy built project to preview
        run: vercel deploy --prebuilt --token=${{ secrets.vercel-token }} > preview-deployment-url.txt

      - id: preview-deployment-url
        name: Output and save preview deployment URL to outputs
        run: |
          cat preview-deployment-url.txt
          echo "url=$(cat preview-deployment-url.txt)" >> "$GITHUB_OUTPUT"

  post-deploy-to-preview-smoke-testing:
    name: 🖥 Post-deploy to preview smoke testing
    runs-on: ubuntu-latest
    needs: deploy-to-preview
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output preview deployment URL
        run: echo ${{needs.deploy-to-preview.outputs.preview-deployment-url}}

      - name: Run smoke tests
        uses: cypress-io/github-action@v6
        with:
          command: yarn test:smoke --config-file cypress.prod.config.js --env CYPRESS_E2E_BASE_URL=${{needs.deploy-to-preview.outputs.preview-deployment-url}}
          wait-on: ${{needs.deploy-to-preview.outputs.preview-deployment-url}}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  deploy:
    name: 🚀 Deploy to production
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    concurrency: deployment
    environment:
      name: Production
      url: https://wentingwang.co.uk
    runs-on: ubuntu-latest
    needs: post-deploy-to-preview-smoke-testing
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull production environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.vercel-token }}

      - name: Build project
        run: vercel build --prod --token=${{ secrets.vercel-token }}

      - name: Deploy built project to production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.vercel-token }}
