name: CD

on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      vercel-org-id:
        required: true
      vercel-project-id:
        required: true

jobs:
  production-deployment:
    name: 🚀 Production deployment
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    concurrency: deployment
    environment:
      name: Production
      url: https://wentingwang.co.uk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull production environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.vercel-token }}

      - name: Build project
        run: vercel build --prod --token=${{ secrets.vercel-token }}

      - name: Deploy built project to production
        run: vercel deploy --prebuilt --prod --token=${{ secrets.vercel-token }}
