name: CI

on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      vercel-org-id:
        required: true
      vercel-project-id:
        required: true

jobs:
  dependencies:
    name: 🏗 Install dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js with Yarn
        id: setup-nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        if: steps.setup-nodejs.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile

  linting:
    name: 🧹 Linting
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies from cache
        run: yarn --offline --frozen-lockfile --ignore-optional --ignore-scripts

      - name: Run linting
        run: yarn lint

  unit-testing:
    name: 🧪 Unit testing
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies from cache
        run: yarn --offline --frozen-lockfile --ignore-optional --ignore-scripts

      - name: Run unit tests
        run: yarn test:unit

  build:
    name: 👷 Build application
    runs-on: ubuntu-latest
    needs: dependencies
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull production environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.vercel-token }}

      - name: Build project
        run: vercel build --prod --token=${{ secrets.vercel-token }}

      - name: Upload built project
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: project
          path: .next

      - name: Upload build output
        if: success() && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: .vercel/output

  end-to-end-testing:
    name: 🖥 End-to-end testing
    runs-on: ubuntu-latest
    needs: build
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies from cache
        run: yarn --offline --frozen-lockfile

      - name: Download built project
        uses: actions/download-artifact@v3
        with:
          name: project
          path: .next

      - name: Run end to end tests
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: yarn start -p 3001
          wait-on: http://localhost:3001/
          command: yarn test:e2e

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
