name: CI

on:
  workflow_call:
    secrets:
      vercel-token:
        required: true
      vercel-org-id:
        required: true
      vercel-project-id:
        required: true

jobs:
  linting:
    name: 🧹 Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies from cache
        run: yarn --frozen-lockfile --ignore-optional --ignore-scripts

      - name: Run linting
        run: yarn lint

  unit-testing:
    name: 🧪 Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies from cache
        run: yarn --frozen-lockfile --ignore-optional --ignore-scripts

      - name: Run unit tests
        run: yarn test:unit

  preview-deployment:
    name: 👀 Preview deployment
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-org-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    environment:
      name: Preview
      url: ${{ steps.preview-deployment-url.outputs.url }}
    outputs:
      preview-deployment-url: ${{ steps.preview-deployment-url.outputs.url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Pull preview environment information
        run: vercel pull --yes --environment=preview --token=${{ secrets.vercel-token }}

      - name: Build project
        run: vercel build --token=${{ secrets.vercel-token }}

      - name: Deploy built project to preview
        run: vercel deploy --prebuilt --token=${{ secrets.vercel-token }} > preview-deployment-url.txt

      - id: preview-deployment-url
        name: Output and save preview deployment URL
        run: |
          cat preview-deployment-url.txt
          echo "url=$(cat preview-deployment-url.txt)" >> "$GITHUB_OUTPUT"

  smoke-testing:
    name: 🖥 Smoke testing for preview
    runs-on: ubuntu-latest
    needs: preview-deployment
    env:
      PREVIEW_DEPLOYMENT_URL: ${{needs.preview-deployment.outputs.preview-deployment-url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Output preview deployment URL
        run: echo $PREVIEW_DEPLOYMENT_URL

      - name: Run smoke tests
        uses: cypress-io/github-action@v6
        with:
          command: yarn test:smoke --config baseUrl=${{env.PREVIEW_DEPLOYMENT_URL}}
          wait-on: ${{env.PREVIEW_DEPLOYMENT_URL}}

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
