name: Dependabot

on:
  pull_request:
  workflow_run:
    workflows: ["CI/CD"]
    types: [completed]
    branches: ["dependabot/**"]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    name: Approve and auto-merge Dependabot PR
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and auto-merge PR
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
