name: Main

on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  cd:
    name: CD
    uses: ./.github/workflows/cd.yml
    needs: [ci]
    secrets:
      vercel-token: ${{ secrets.VERCEL_TOKEN }}
      vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
      vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
